.TH READ-QUICKLY 1 READ-QUICKLY
.SH NAME
read-quickly \- read quickly
.SH SYNOPSIS
.B read-quickly
.RI [ file ]
.SH DESCRIPTION
Displays a plain-text file word-by-word in the middle
of the terminal. Words are automatically paged in a
specifiable rate, by default 2 words per second.
This is a bit slow, you should turn it up when
gradually until your performance has been optimised.
Repeated words will be indicated by alternating reverse
video highlighting.
.PP
Escape sequences are printed as-is.
.PP
If no file is specified, or if \- i specified,
stdin will be paged.
.PP
.B read-quickly
uses a method called rapid serial visual presentation.
.SH OPTIONS
None.
.SH ENVIRONMENT
.TP
.B READ_QUICKLY_RATE
The rate at which the words will be printed.
Defaults to 120 words per minute.
.br
.br
This should a positive integer, optionally
followed by a unit. If no unit is specified,
words per minute will be used. Valid units
are (case-insensitive):
.RS 14
.TP
.B wpm
.TQ
.B w/m
.TQ
.B m
.TQ
.B wpmin
.TQ
.B w/min
.TQ
.B /min
Words per minute.
.PP
.TP
.B wpsec
.TQ
.B w/sec
.TQ
.B sec
.TQ
.B wps
.TQ
.B w/s
.TQ
.B /s
.TQ
.B Hz
Words per second.
.Re
.fi
.SH COMMANDS
.TP
.B \+
Increase word rate.
.TP
.B \-
Decrease word rate.
.TP
.B p
Pause/resume.
.TP
.B q
Exit.
.TP
.BR left ,\  up
Go to the previous word.
.TP
.BR right ,\  down
Go to next previous word.
.SH RATIONALE
This should be obvious.
.SH SEE ALSO
No similar or otherwise related work known.
Please inform me if you know any. There probably
is a bunch.
